# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(983, 659)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(965, 0))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(500, 141))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_14.addWidget(self.label)
        self.doubleSpinBox_Betta = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Betta.setObjectName(_fromUtf8("doubleSpinBox_Betta"))
        self.horizontalLayout_14.addWidget(self.doubleSpinBox_Betta)
        self.checkBox_Replace_Betta = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_Replace_Betta.setObjectName(_fromUtf8("checkBox_Replace_Betta"))
        self.horizontalLayout_14.addWidget(self.checkBox_Replace_Betta)
        self.gridLayout.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_29.addWidget(self.label_4)
        self.spinBox_ZPst = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_ZPst.setMaximum(1)
        self.spinBox_ZPst.setObjectName(_fromUtf8("spinBox_ZPst"))
        self.horizontalLayout_29.addWidget(self.spinBox_ZPst)
        self.gridLayout.addLayout(self.horizontalLayout_29, 1, 2, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_17.addWidget(self.label_2)
        self.spinBox_RPon = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_RPon.setMaximum(1)
        self.spinBox_RPon.setObjectName(_fromUtf8("spinBox_RPon"))
        self.horizontalLayout_17.addWidget(self.spinBox_RPon)
        self.gridLayout.addLayout(self.horizontalLayout_17, 1, 1, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_18.addWidget(self.label_10)
        self.spinBox_Readhiness = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_Readhiness.setMaximum(1)
        self.spinBox_Readhiness.setObjectName(_fromUtf8("spinBox_Readhiness"))
        self.horizontalLayout_18.addWidget(self.spinBox_Readhiness)
        self.gridLayout.addLayout(self.horizontalLayout_18, 1, 0, 1, 1)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_32.addWidget(self.label_23)
        self.spinBox_Mode = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_Mode.setMaximum(1)
        self.spinBox_Mode.setObjectName(_fromUtf8("spinBox_Mode"))
        self.horizontalLayout_32.addWidget(self.spinBox_Mode)
        self.gridLayout.addLayout(self.horizontalLayout_32, 2, 3, 1, 1)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_24.addWidget(self.label_12)
        self.spinBox_OPst = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_OPst.setMaximum(1)
        self.spinBox_OPst.setObjectName(_fromUtf8("spinBox_OPst"))
        self.horizontalLayout_24.addWidget(self.spinBox_OPst)
        self.gridLayout.addLayout(self.horizontalLayout_24, 1, 3, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_23.addWidget(self.label_11)
        self.spinBox_LockDv = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_LockDv.setMaximum(1)
        self.spinBox_LockDv.setObjectName(_fromUtf8("spinBox_LockDv"))
        self.horizontalLayout_23.addWidget(self.spinBox_LockDv)
        self.gridLayout.addLayout(self.horizontalLayout_23, 2, 0, 1, 1)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_30.addWidget(self.label_21)
        self.spinBox_ROP = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_ROP.setMaximum(1)
        self.spinBox_ROP.setObjectName(_fromUtf8("spinBox_ROP"))
        self.horizontalLayout_30.addWidget(self.spinBox_ROP)
        self.gridLayout.addLayout(self.horizontalLayout_30, 2, 1, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_25.addWidget(self.label_7)
        self.spinBox_KZ_OB = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_KZ_OB.setMaximum(1)
        self.spinBox_KZ_OB.setObjectName(_fromUtf8("spinBox_KZ_OB"))
        self.horizontalLayout_25.addWidget(self.spinBox_KZ_OB)
        self.gridLayout.addLayout(self.horizontalLayout_25, 2, 2, 1, 1)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_31.addWidget(self.label_22)
        self.spinBox_AKA_IP4 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_AKA_IP4.setMaximum(1)
        self.spinBox_AKA_IP4.setObjectName(_fromUtf8("spinBox_AKA_IP4"))
        self.horizontalLayout_31.addWidget(self.spinBox_AKA_IP4)
        self.gridLayout.addLayout(self.horizontalLayout_31, 3, 0, 1, 1)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_33.addWidget(self.label_24)
        self.spinBox_AKA_IP2 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_AKA_IP2.setMaximum(1)
        self.spinBox_AKA_IP2.setObjectName(_fromUtf8("spinBox_AKA_IP2"))
        self.horizontalLayout_33.addWidget(self.spinBox_AKA_IP2)
        self.gridLayout.addLayout(self.horizontalLayout_33, 3, 2, 1, 1)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_34.addWidget(self.label_25)
        self.spinBox_AKA_IP1 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_AKA_IP1.setMaximum(1)
        self.spinBox_AKA_IP1.setObjectName(_fromUtf8("spinBox_AKA_IP1"))
        self.horizontalLayout_34.addWidget(self.spinBox_AKA_IP1)
        self.gridLayout.addLayout(self.horizontalLayout_34, 3, 3, 1, 1)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_35.addWidget(self.label_26)
        self.spinBox_AKA_IP3 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_AKA_IP3.setMaximum(1)
        self.spinBox_AKA_IP3.setObjectName(_fromUtf8("spinBox_AKA_IP3"))
        self.horizontalLayout_35.addWidget(self.spinBox_AKA_IP3)
        self.gridLayout.addLayout(self.horizontalLayout_35, 3, 1, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_16.addWidget(self.label_3)
        self.spinBox_BSB = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_BSB.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spinBox_BSB.setObjectName(_fromUtf8("spinBox_BSB"))
        self.horizontalLayout_16.addWidget(self.spinBox_BSB)
        self.gridLayout.addLayout(self.horizontalLayout_16, 0, 1, 1, 1)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_22.addWidget(self.label_5)
        self.spinBox_R_W = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_R_W.setProperty("value", 1)
        self.spinBox_R_W.setObjectName(_fromUtf8("spinBox_R_W"))
        self.horizontalLayout_22.addWidget(self.spinBox_R_W)
        self.gridLayout.addLayout(self.horizontalLayout_22, 0, 2, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_26.addWidget(self.label_6)
        self.spinBox_OM = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_OM.setObjectName(_fromUtf8("spinBox_OM"))
        self.horizontalLayout_26.addWidget(self.spinBox_OM)
        self.gridLayout.addLayout(self.horizontalLayout_26, 0, 3, 1, 1)
        self.horizontalLayout_15.addLayout(self.gridLayout)
        self.horizontalLayout_6.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_SendKvitokWirteFlash = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_SendKvitokWirteFlash.setObjectName(_fromUtf8("pushButton_SendKvitokWirteFlash"))
        self.verticalLayout_2.addWidget(self.pushButton_SendKvitokWirteFlash)
        self.checkBox_AutoanswerWriteFlash = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_AutoanswerWriteFlash.setObjectName(_fromUtf8("checkBox_AutoanswerWriteFlash"))
        self.verticalLayout_2.addWidget(self.checkBox_AutoanswerWriteFlash)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_SendReadDataFlash = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_SendReadDataFlash.setObjectName(_fromUtf8("pushButton_SendReadDataFlash"))
        self.verticalLayout_4.addWidget(self.pushButton_SendReadDataFlash)
        self.checkBox_AutoanswerReadFlash = QtGui.QCheckBox(self.groupBox_6)
        self.checkBox_AutoanswerReadFlash.setObjectName(_fromUtf8("checkBox_AutoanswerReadFlash"))
        self.verticalLayout_4.addWidget(self.checkBox_AutoanswerReadFlash)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.horizontalLayout_6.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 983, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMouseTracking(True)
        self.toolBar.setAcceptDrops(True)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget_Net = QtGui.QDockWidget(MainWindow)
        self.dockWidget_Net.setAutoFillBackground(False)
        self.dockWidget_Net.setFloating(False)
        self.dockWidget_Net.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_Net.setObjectName(_fromUtf8("dockWidget_Net"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.groupBox_Net = QtGui.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Net.sizePolicy().hasHeightForWidth())
        self.groupBox_Net.setSizePolicy(sizePolicy)
        self.groupBox_Net.setMinimumSize(QtCore.QSize(163, 0))
        self.groupBox_Net.setObjectName(_fromUtf8("groupBox_Net"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_Net)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_IP_4 = QtGui.QLabel(self.groupBox_Net)
        self.label_IP_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_IP_4.setObjectName(_fromUtf8("label_IP_4"))
        self.horizontalLayout_9.addWidget(self.label_IP_4)
        self.lineEditIpAddressBind = QtGui.QLineEdit(self.groupBox_Net)
        self.lineEditIpAddressBind.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditIpAddressBind.setMaxLength(15)
        self.lineEditIpAddressBind.setObjectName(_fromUtf8("lineEditIpAddressBind"))
        self.horizontalLayout_9.addWidget(self.lineEditIpAddressBind)
        self.spinBox_Port_Bind = QtGui.QSpinBox(self.groupBox_Net)
        self.spinBox_Port_Bind.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBox_Port_Bind.setMinimum(1024)
        self.spinBox_Port_Bind.setMaximum(54000)
        self.spinBox_Port_Bind.setProperty("value", 11000)
        self.spinBox_Port_Bind.setObjectName(_fromUtf8("spinBox_Port_Bind"))
        self.horizontalLayout_9.addWidget(self.spinBox_Port_Bind)
        self.verticalLayout_10.addWidget(self.groupBox_Net)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonStartNet = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButtonStartNet.setAutoFillBackground(False)
        self.pushButtonStartNet.setObjectName(_fromUtf8("pushButtonStartNet"))
        self.horizontalLayout.addWidget(self.pushButtonStartNet)
        self.pushButtonStopNet = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButtonStopNet.setObjectName(_fromUtf8("pushButtonStopNet"))
        self.horizontalLayout.addWidget(self.pushButtonStopNet)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.dockWidget_Net.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_Net)
        self.dockWidget_Output = QtGui.QDockWidget(MainWindow)
        self.dockWidget_Output.setFloating(False)
        self.dockWidget_Output.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_Output.setObjectName(_fromUtf8("dockWidget_Output"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.plainTextEdit_log = QtGui.QPlainTextEdit(self.dockWidgetContents_2)
        self.plainTextEdit_log.setReadOnly(True)
        self.plainTextEdit_log.setObjectName(_fromUtf8("plainTextEdit_log"))
        self.verticalLayout_5.addWidget(self.plainTextEdit_log)
        self.dockWidget_Output.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_Output)
        self.dockWidget_Serial = QtGui.QDockWidget(MainWindow)
        self.dockWidget_Serial.setFloating(False)
        self.dockWidget_Serial.setObjectName(_fromUtf8("dockWidget_Serial"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.groupBox_Serial = QtGui.QGroupBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Serial.sizePolicy().hasHeightForWidth())
        self.groupBox_Serial.setSizePolicy(sizePolicy)
        self.groupBox_Serial.setMinimumSize(QtCore.QSize(163, 0))
        self.groupBox_Serial.setObjectName(_fromUtf8("groupBox_Serial"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_Serial)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_8 = QtGui.QLabel(self.groupBox_Serial)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.comboBox_ListPorts = QtGui.QComboBox(self.groupBox_Serial)
        self.comboBox_ListPorts.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_ListPorts.setObjectName(_fromUtf8("comboBox_ListPorts"))
        self.horizontalLayout_3.addWidget(self.comboBox_ListPorts)
        self.label_9 = QtGui.QLabel(self.groupBox_Serial)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_3.addWidget(self.label_9)
        self.comboBox_BaudRate = QtGui.QComboBox(self.groupBox_Serial)
        self.comboBox_BaudRate.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_BaudRate.setObjectName(_fromUtf8("comboBox_BaudRate"))
        self.horizontalLayout_3.addWidget(self.comboBox_BaudRate)
        self.label_20 = QtGui.QLabel(self.groupBox_Serial)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_3.addWidget(self.label_20)
        self.comboBox_DataBits = QtGui.QComboBox(self.groupBox_Serial)
        self.comboBox_DataBits.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_DataBits.setObjectName(_fromUtf8("comboBox_DataBits"))
        self.horizontalLayout_3.addWidget(self.comboBox_DataBits)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_18 = QtGui.QLabel(self.groupBox_Serial)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_5.addWidget(self.label_18)
        self.comboBox_Parity = QtGui.QComboBox(self.groupBox_Serial)
        self.comboBox_Parity.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_Parity.setObjectName(_fromUtf8("comboBox_Parity"))
        self.horizontalLayout_5.addWidget(self.comboBox_Parity)
        self.label_19 = QtGui.QLabel(self.groupBox_Serial)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_5.addWidget(self.label_19)
        self.comboBox_StopBits = QtGui.QComboBox(self.groupBox_Serial)
        self.comboBox_StopBits.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_StopBits.setObjectName(_fromUtf8("comboBox_StopBits"))
        self.horizontalLayout_5.addWidget(self.comboBox_StopBits)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_11.addWidget(self.groupBox_Serial)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButtonStart_Serial = QtGui.QPushButton(self.dockWidgetContents_3)
        self.pushButtonStart_Serial.setAutoFillBackground(False)
        self.pushButtonStart_Serial.setObjectName(_fromUtf8("pushButtonStart_Serial"))
        self.horizontalLayout_4.addWidget(self.pushButtonStart_Serial)
        self.pushButtonStop_Serial = QtGui.QPushButton(self.dockWidgetContents_3)
        self.pushButtonStop_Serial.setObjectName(_fromUtf8("pushButtonStop_Serial"))
        self.horizontalLayout_4.addWidget(self.pushButtonStop_Serial)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.dockWidget_Serial.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_Serial)
        self.dockWidget_Common = QtGui.QDockWidget(MainWindow)
        self.dockWidget_Common.setObjectName(_fromUtf8("dockWidget_Common"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox_Autoanswer = QtGui.QCheckBox(self.dockWidgetContents_4)
        self.checkBox_Autoanswer.setChecked(True)
        self.checkBox_Autoanswer.setObjectName(_fromUtf8("checkBox_Autoanswer"))
        self.verticalLayout_3.addWidget(self.checkBox_Autoanswer)
        self.dockWidget_Common.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_Common)
        self.dockWidget_LogCmd = QtGui.QDockWidget(MainWindow)
        self.dockWidget_LogCmd.setFloating(False)
        self.dockWidget_LogCmd.setObjectName(_fromUtf8("dockWidget_LogCmd"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tableView = QtGui.QTableView(self.dockWidgetContents_5)
        self.tableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout_6.addWidget(self.tableView)
        self.dockWidget_LogCmd.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_LogCmd)
        self.actionDebug = QtGui.QAction(MainWindow)
        self.actionDebug.setObjectName(_fromUtf8("actionDebug"))
        self.menu.addAction(self.actionDebug)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Имитатор МУС200", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Рабочий АК", None))
        self.label.setText(_translate("MainWindow", "β тек =", None))
        self.checkBox_Replace_Betta.setText(_translate("MainWindow", "зам.", None))
        self.label_4.setText(_translate("MainWindow", "ЗП Ст =", None))
        self.label_2.setText(_translate("MainWindow", "РП вкл =", None))
        self.label_10.setText(_translate("MainWindow", "Готовность =", None))
        self.label_23.setText(_translate("MainWindow", "Режим =", None))
        self.label_12.setText(_translate("MainWindow", "ОП Ст =", None))
        self.label_11.setText(_translate("MainWindow", "Блокир. Дв. =", None))
        self.label_21.setText(_translate("MainWindow", "РОП =", None))
        self.label_7.setText(_translate("MainWindow", "КЗ ОВ =", None))
        self.label_22.setText(_translate("MainWindow", "АКА ИП4 =", None))
        self.label_24.setText(_translate("MainWindow", "АКА ИП2=", None))
        self.label_25.setText(_translate("MainWindow", "АКА ИП1=", None))
        self.label_26.setText(_translate("MainWindow", "АКА ИП3 =", None))
        self.label_3.setText(_translate("MainWindow", "BSB =", None))
        self.label_5.setText(_translate("MainWindow", "R/w =", None))
        self.label_6.setText(_translate("MainWindow", "om = ", None))
        self.groupBox.setTitle(_translate("MainWindow", "Flash память", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Запись Flash", None))
        self.pushButton_SendKvitokWirteFlash.setText(_translate("MainWindow", "Отправить квиток успешной записи", None))
        self.checkBox_AutoanswerWriteFlash.setText(_translate("MainWindow", "автоответ", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Чтение Flash", None))
        self.pushButton_SendReadDataFlash.setText(_translate("MainWindow", "Отправить прочитанные данные", None))
        self.checkBox_AutoanswerReadFlash.setText(_translate("MainWindow", "автоответ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1", None))
        self.menu.setTitle(_translate("MainWindow", "Справка", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.dockWidget_Net.setWindowTitle(_translate("MainWindow", "Сеть", None))
        self.groupBox_Net.setTitle(_translate("MainWindow", "адрес приема данных", None))
        self.label_IP_4.setText(_translate("MainWindow", "IP = ", None))
        self.lineEditIpAddressBind.setInputMask(_translate("MainWindow", "000.000.000.000", None))
        self.lineEditIpAddressBind.setText(_translate("MainWindow", "127.0.0.1", None))
        self.pushButtonStartNet.setText(_translate("MainWindow", "Старт", None))
        self.pushButtonStopNet.setText(_translate("MainWindow", "Стоп", None))
        self.dockWidget_Output.setWindowTitle(_translate("MainWindow", "Вывод", None))
        self.dockWidget_Serial.setWindowTitle(_translate("MainWindow", "Com порт", None))
        self.groupBox_Serial.setTitle(_translate("MainWindow", "адрес приема данных", None))
        self.label_8.setText(_translate("MainWindow", "Порт", None))
        self.label_9.setText(_translate("MainWindow", "Скорость", None))
        self.label_20.setText(_translate("MainWindow", "Биты данных", None))
        self.label_18.setText(_translate("MainWindow", "Четность", None))
        self.label_19.setText(_translate("MainWindow", "Стопбит", None))
        self.pushButtonStart_Serial.setText(_translate("MainWindow", "Старт", None))
        self.pushButtonStop_Serial.setText(_translate("MainWindow", "Стоп", None))
        self.dockWidget_Common.setWindowTitle(_translate("MainWindow", "Общие", None))
        self.checkBox_Autoanswer.setText(_translate("MainWindow", "автоответ", None))
        self.dockWidget_LogCmd.setWindowTitle(_translate("MainWindow", "Журнла команд", None))
        self.actionDebug.setText(_translate("MainWindow", "Отладка", None))
        self.actionDebug.setShortcut(_translate("MainWindow", "F5", None))

